services:
  db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppass
    networks: [wpnet]
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  wordpress1:
    image: wordpress:5.4.2-php7.2-apache
    container_name: wordpress1
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppass
      WORDPRESS_DB_NAME: wordpress
    networks: [wpnet]
    volumes:
      - ./wp-content:/var/www/html/wp-content

  wordpress2:
    image: wordpress:5.4.2-php7.2-apache
    container_name: wordpress2
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppass
      WORDPRESS_DB_NAME: wordpress
    networks: [wpnet]
    volumes:
      - ./wp-content:/var/www/html/wp-content

  wordpress3:
    image: wordpress:5.4.2-php7.2-apache
    container_name: wordpress3
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppass
      WORDPRESS_DB_NAME: wordpress
    networks: [wpnet]
    volumes:
      - ./wp-content:/var/www/html/wp-content

  nginx:
    image: nginx:1.19.0
    container_name: nginx
    depends_on:
      - wordpress1
      - wordpress2
      - wordpress3
    ports:
      - "8080:80"
    networks: [wpnet]
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  locust-master:
    image: locustio/locust
    container_name: locust-master
    depends_on:
      - nginx
    ports:
      - "8089:8089"
    volumes:
      - ./locustfile.py:/mnt/locust/locustfile.py:ro
    command: -f /mnt/locust/locustfile.py --master --host=http://host.docker.internal:8080
    networks: [wpnet]

  locust-worker:
    image: locustio/locust
    container_name: locust-worker
    depends_on:
      - locust-master
    volumes:
      - ./locustfile.py:/mnt/locust/locustfile.py:ro
    command: -f /mnt/locust/locustfile.py --worker --master-host=locust-master
    networks: [wpnet]

volumes:
  db_data:

networks:
  wpnet:
    driver: bridge
