version: "3.8"

services:
  db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppass
    networks:
      - wpnet
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  wordpress1:
    image: wordpress:5.4.2-php7.2-apache
    container_name: wordpress1
    depends_on:
      db:
        condition: service_healthy
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppass
      WORDPRESS_DB_NAME: wordpress
      WP_HOME: http://localhost:8080
      WP_SITEURL: http://localhost:8080
    networks:
      - wpnet

  wordpress2:
    image: wordpress:5.4.2-php7.2-apache
    container_name: wordpress2
    depends_on:
      db:
        condition: service_healthy
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppass
      WORDPRESS_DB_NAME: wordpress
      WP_HOME: http://localhost:8080
      WP_SITEURL: http://localhost:8080
    networks:
      - wpnet

  wordpress3:
    image: wordpress:5.4.2-php7.2-apache
    container_name: wordpress3
    depends_on:
      db:
        condition: service_healthy
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppass
      WORDPRESS_DB_NAME: wordpress
      WP_HOME: http://localhost:8080
      WP_SITEURL: http://localhost:8080
    networks:
      - wpnet

  nginx:
    image: nginx:1.19.0
    container_name: nginx
    depends_on:
      - wordpress1
      - wordpress2
      - wordpress3
    ports:
      - "8080:80" # Porta do WordPress
    networks:
      - wpnet
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  # --- SERVIÇOS DO LOCUST ADICIONADOS AQUI ---

  locust-master:
    image: locustio/locust
    ports:
      - "8089:8089" # Porta da interface Web do Locust
    volumes:
      - ./locustfile.py:/mnt/locust/locustfile.py
    # O --host aponta para o nome do seu serviço Nginx
    command: -f /mnt/locust/locustfile.py --master --host=http://nginx
    networks:
      - wpnet # Precisa estar na mesma rede do Nginx

  locust-worker:
    image: locustio/locust
    # Não precisa de portas, fala direto com o master
    volumes:
      - ./locustfile.py:/mnt/locust/locustfile.py
    # Aponta para o nome do serviço master
    command: -f /mnt/locust/locustfile.py --worker --master-host=locust-master
    networks:
      - wpnet # Precisa estar na mesma rede

volumes:
  db_data:

networks:
  wpnet:
    driver: bridge